-- ============================================================
-- Municipal Data Schema — PostgreSQL (Enhanced)
-- ============================================================

-- 1. Required extension for EXCLUDE constraint (daterange + gist)
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- types and possible values
CREATE TYPE party_type AS ENUM (
  'democrat', 'republican', 'independent', 'dsa'
);
CREATE TYPE resolution_status AS ENUM (
  'introduced', 'in_committee', 'passed', 'failed', 'tabled', 'passed_as_amended'
);
CREATE TYPE vote_type AS ENUM (
  'yea', 'nay', 'abstain', 'absent'
);

CREATE TABLE city (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT    NOT NULL,
  state       CHAR(2) NOT NULL,
  UNIQUE (name, state)
);

CREATE TABLE ward (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number      INT     NOT NULL,
  city_id     INT     NOT NULL REFERENCES city(id) ON DELETE CASCADE,
  UNIQUE (number, city_id)
);

CREATE TABLE alderman (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name  TEXT    NOT NULL,
  last_name   TEXT    NOT NULL,
  party       party_type NOT NULL DEFAULT 'independent',
  email       TEXT,
  photo_url   TEXT,
  ward_id     INT     NOT NULL REFERENCES ward(id) ON DELETE RESTRICT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE alderman_term (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alderman_id INT     NOT NULL REFERENCES alderman(id) ON DELETE CASCADE,
  ward_id     INT     NOT NULL REFERENCES ward(id) ON DELETE RESTRICT,
  term_start  DATE    NOT NULL,
  term_end    DATE,
  -- NOTE: PostgreSQL requires IMMUTABLE expressions for GENERATED STORED columns.
  -- CURRENT_DATE is STABLE, so we keep the trigger for time-aware derivation.
  active      BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Prevent overlapping terms for the same ward seat
  EXCLUDE USING gist (
    ward_id WITH =,
    daterange(term_start, COALESCE(term_end, 'infinity'::date)) WITH &&
  ),

  -- Business logic: end date cannot precede start date
  CONSTRAINT chk_term_dates CHECK (term_end IS NULL OR term_end >= term_start)
);

-- Trigger to keep `active` in sync with term_end
CREATE OR REPLACE FUNCTION alderman_term_active_trigger()
RETURNS TRIGGER AS $$
BEGIN
  NEW.active := (NEW.term_end IS NULL OR NEW.term_end >= CURRENT_DATE);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_alderman_term_active
BEFORE INSERT OR UPDATE OF term_end ON alderman_term
FOR EACH ROW
EXECUTE FUNCTION alderman_term_active_trigger();

CREATE TABLE resolution (
  id                      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_resolution_id    INT     REFERENCES resolution(id) ON DELETE CASCADE,
  amendment_number        INT,
  resolution_number       TEXT    NOT NULL,
  city_id                 INT     NOT NULL REFERENCES city(id) ON DELETE CASCADE,
  title                   TEXT    NOT NULL,
  description             TEXT,
  link                    TEXT,
  status                  resolution_status NOT NULL DEFAULT 'introduced',
  introduced_date         DATE    NOT NULL DEFAULT CURRENT_DATE,
  passed_date             DATE,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- Each amendment number is unique within its parent resolution
  UNIQUE (parent_resolution_id, amendment_number),

  -- Enforce logical consistency between status and passed_date
  CONSTRAINT chk_resolution_dates_status CHECK (
    (status IN ('passed', 'passed_as_amended') AND passed_date IS NOT NULL) OR
    (status NOT IN ('passed', 'passed_as_amended') AND passed_date IS NULL)
  )
);

-- Partial index: base resolutions (no parent) must have unique resolution_number per city
CREATE UNIQUE INDEX idx_resolution_number_city
ON resolution (resolution_number, city_id)
WHERE parent_resolution_id IS NULL;

CREATE TABLE resolution_endorser (
  resolution_id   INT NOT NULL REFERENCES resolution(id) ON DELETE CASCADE,
  alderman_id     INT NOT NULL REFERENCES alderman(id) ON DELETE CASCADE,
  PRIMARY KEY (resolution_id, alderman_id)
);

CREATE TABLE vote (
  id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  resolution_id   INT         NOT NULL REFERENCES resolution(id) ON DELETE CASCADE,
  alderman_id     INT         NOT NULL REFERENCES alderman(id) ON DELETE CASCADE,
  vote            vote_type   NOT NULL,
  meeting_date    DATE        NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (resolution_id, alderman_id)
);

-- Indexes for common queries
CREATE INDEX idx_alderman_term_alderman   ON alderman_term (alderman_id);
CREATE INDEX idx_alderman_term_ward       ON alderman_term (ward_id);
CREATE INDEX idx_alderman_term_active     ON alderman_term (active) WHERE active = true;
CREATE INDEX idx_resolution_city          ON resolution (city_id);
CREATE INDEX idx_resolution_status        ON resolution (status);
CREATE INDEX idx_resolution_parent        ON resolution (parent_resolution_id);
CREATE INDEX idx_resolution_introduced    ON resolution (introduced_date);
CREATE INDEX idx_resolution_number_search ON resolution (resolution_number);
CREATE INDEX idx_vote_alderman            ON vote (alderman_id);
CREATE INDEX idx_vote_meeting_date        ON vote (meeting_date);

-- Helpers: auto-update updated_at
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Safer dynamic trigger creation
DO $$
DECLARE
  t RECORD;
BEGIN
  FOR t IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.tables tbl
      ON c.table_name = tbl.table_name AND c.table_schema = tbl.table_schema
    WHERE c.column_name = 'updated_at'
      AND c.table_schema = 'public'
      AND tbl.table_type = 'BASE TABLE'
  LOOP
    EXECUTE format(
      'CREATE TRIGGER trg_%s_updated_at
       BEFORE UPDATE ON %I
       FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
      t.table_name, t.table_name
    );
  END LOOP;
END;
$$;
